"""External evidence inequalities. Teaching constants, not policy."""

FINDING_NE_AUTHORIZATION = "FINDING != AUTHORIZATION"
EVALUATION_NE_AUTHORIZATION = "EVALUATION != AUTHORIZATION"
INVENTORY_NE_TRUST = "INVENTORY != TRUST"
SCANNER_HIGH_NE_DENY = "SCANNER HIGH != DENY"
SCANNER_LOW_NE_ALLOW = "SCANNER LOW != ALLOW"
ZERO_FINDINGS_NE_SAFE = "ZERO FINDINGS != SAFE"
PASSING_EVALUATION_NE_SAFE = "PASSING EVALUATION != SAFE"
EXTERNAL_TOOL_NE_PDP = "EXTERNAL TOOL != PDP"
SPLUNK_NE_PDP = "SPLUNK != PDP"
HASH_MATCH_NE_CAUSALITY = (
    "HASH MATCH = compared canonical content matched; not same process, "
    "runtime, request, execution, or security decision."
)

SEMANTIC_INVARIANTS = (
    FINDING_NE_AUTHORIZATION,
    EVALUATION_NE_AUTHORIZATION,
    INVENTORY_NE_TRUST,
    SCANNER_HIGH_NE_DENY,
    SCANNER_LOW_NE_ALLOW,
    ZERO_FINDINGS_NE_SAFE,
    PASSING_EVALUATION_NE_SAFE,
    EXTERNAL_TOOL_NE_PDP,
    SPLUNK_NE_PDP,
)
